# Root workspace Cargo.toml
[workspace]
resolver = "2"
members = [
	"crates/cache",
	"crates/config",
	"crates/encrypt",
	"crates/http",
	"crates/pipeline",
	"crates/process",
	"crates/queue",
	"crates/settings",
	"crates/store",
	"crates/strings",
	"crates/testing",
	"crates/workflows",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
