[workspace]
members = [
	"crates/config",
	"crates/encrypt",
	"crates/pipeline",
	"crates/queue",
	"crates/settings",
	"crates/store",
	"crates/testing",
	"crates/workflows",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/find-how/support"
documentation = "https://docs.rs/support"
homepage = "https://github.com/find-how/support"
